name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 3.1.2
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: ruby test/run_test.rb
      - name: Run RSpec Tests
        run: bundle exec rspec test
